-- Dedicated Snowflake service user for Lightdash
-- Run this in a Snowflake worksheet as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

-- Reuse the existing read-only reporting role.
CREATE ROLE IF NOT EXISTS REPORTER;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;

-- Create a dedicated Lightdash service user and register its public key.
CREATE USER IF NOT EXISTS LIGHTDASH
  LOGIN_NAME='lightdash'
  TYPE=SERVICE
  RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArN6NMHCBOQXunhRjJDHTbp/86dbPZqs4/tcY8VuEMasnfJRM0L6FxDKyVbRXKZPglyk2Uk0trTpm3+4JbAI62rKV7FFVe64u+D6ZnC8UPT4mPtkiRyCDwDVvWfz+R83jCF1cBGIkoATkDGasmK6LR58CYKg0/vOeGU4n+tBwOZJM42qjg2pAeZ6li/nKHe+D8TXSpCiCncy6DfHgIStapKWgbaqW8jx5kjc1RXIRuxVUWACG+YpV0OyzjCKL/cjDdOqaMUuZkSilMVt6QqYfSvzmdIAJm60phnRjC+UoSe6qA5UzBcMPfIeG1a3ZADEl7MMIMvbRBmu2f7rDLzFVawIDAQAB'
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=REPORTER
  DEFAULT_NAMESPACE='OLIST.DEV'
  COMMENT='Lightdash read-only service user';

ALTER USER LIGHTDASH SET
  RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArN6NMHCBOQXunhRjJDHTbp/86dbPZqs4/tcY8VuEMasnfJRM0L6FxDKyVbRXKZPglyk2Uk0trTpm3+4JbAI62rKV7FFVe64u+D6ZnC8UPT4mPtkiRyCDwDVvWfz+R83jCF1cBGIkoATkDGasmK6LR58CYKg0/vOeGU4n+tBwOZJM42qjg2pAeZ6li/nKHe+D8TXSpCiCncy6DfHgIStapKWgbaqW8jx5kjc1RXIRuxVUWACG+YpV0OyzjCKL/cjDdOqaMUuZkSilMVt6QqYfSvzmdIAJm60phnRjC+UoSe6qA5UzBcMPfIeG1a3ZADEl7MMIMvbRBmu2f7rDLzFVawIDAQAB',
  DEFAULT_WAREHOUSE='COMPUTE_WH',
  DEFAULT_ROLE=REPORTER,
  DEFAULT_NAMESPACE='OLIST.DEV';

GRANT ROLE REPORTER TO USER LIGHTDASH;

-- Ensure REPORTER remains read-only for the analytics layer.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE OLIST TO ROLE REPORTER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OLIST TO ROLE REPORTER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE OLIST TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST.DEV TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST.DEV TO ROLE REPORTER;

-- Optional verification
DESC USER LIGHTDASH;
